<?= $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('size-guide')
    ->toHtml();
?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ], function ($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Size guide',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#click-me").on('click', function () {
                $("#popup-modal").modal("openModal");
            });

        }
    );
</script>
