<div class="social-media-icons">

    <!-- Facebook -->
    <a href="https://www.facebook.com/" title="Share on facebook">
        <i class="fa fa-facebook" aria-hidden="true"></i>
        share face
    </a>
    <!-- TWITTER -->
    <a href="http://twitter.com" title="Share on Twitter">
        <i class="fa fa-twitter" aria-hidden="true"></i> Share tw </a>
    <!-- instagram -->
    <a href="https://www.instagram.com/" title="Share on instagram">
        <i class="fa fa-instagram" aria-hidden="true"></i> Share ins </a>
</div>