<div class="social-media-icons">

    <!-- Facebook -->
    <a href="https://www.facebook.com/" title="Share on facebook"><i class="fab fa-facebook-f"></i>
    </a>
    <!-- TWITTER -->
    <a href="http://twitter.com" title="Share on Twitter"><i class="fab fa-twitter"></i></a>
    <!-- instagram -->
    <a href="https://www.instagram.com/" title="Share on instagram"><i class="fab fa-instagram"></i> </a>
</div>