<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()) :?>
<div class="message info empty">
    <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
</div>
<?php else :?>
<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>

<?php
    if ($block->getMode() == 'grid') {
        $modenew='';
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $modenew='products-grid-3';
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    
    ?>
<div
    class="products wrapper product-list-mkod <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?> <?= /* @noEscape */ $modenew ?>">
    <ol class="products list items product-items">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product) :?>
        <li class="item product product-item">
            <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                <?php // Product Image ?>
                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo"
                    tabindex="-1">
                    <?= $productImage->toHtml() ?>
                </a>
                <div class="product details product-item-details">
                    <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                    <strong class="product name product-item-name">
                        <a class="product-item-link" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </strong>
                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                    <?php if ($_product->isAvailable()) :?>
                    <?= $block->getProductDetailsHtml($_product) ?>
                    <?php endif; ?>

                    <div class="product-item-inner">
                        <div class="view">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>">View</a>
                        </div>
                        <div class="box">
                            <div class="line"></div>
                        </div>    

                        <div class="product actions product-item-actions"
                            <?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                            <div class="actions-primary"
                                <?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <?php if ($_product->isSaleable()) :?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form"
                                    data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                    action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                    <input type="hidden" name="product"
                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                        value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                        class="action tocart primary">
                                        <span><?= $block->escapeHtml(__('Buy')) ?></span>
                                    </button>
                                </form>
                                <?php else :?>
                                <?php if ($_product->isAvailable()) :?>
                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span>
                                </div>
                                <?php else :?>
                                <div class="stock unavailable">
                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            
                        </div>
                        <?php if ($showDescription) :?>
                        <div class="product description product-item-description">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                title="<?= /* @noEscape */ $_productNameStripped ?>"
                                class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </li>
        <?php endforeach; ?>
    </ol>
</div>
<?= $block->getToolbarHtml() ?>
<?php if (!$block->isRedirectToCartEnabled()) :?>
<script type="text/x-magento-init">
    {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
</script>
<?php endif; ?>
<?php endif; ?>
<!-- <script type="text/javascript">
    
    $( document ).ready(function() {
        var placeholderTop = placeholder.offset().top;
        var viewTop = view.scrollTop();
        if (
            (viewTop > placeholderTop) &&
            !message.is( ".site-message-fixed" )
            ){


            placeholder.height(
                placeholder.height()
            );

            // Make the message fixed.
            message.addClass( "site-message-fixed" );

        // Check to see if the view has scroll back up
        // above the message AND that the message is
        // currently fixed.
        } else if (
            (viewTop <= placeholderTop) &&
            message.is( ".site-message-fixed" )
            ){

            // Make the placeholder height auto again.
            placeholder.css( "height", "auto" );

            // Remove the fixed position class on the
            // message. This will pop it back into its
            // static position.
            message.removeClass( "site-message-fixed" );

        }
    });
}); -->
<script type="text/javascript" src="jquery-1.4a2.js"></script>
<script type="text/javascript">

		jQuery(function( $ ){
			var placeholder = $( ".product-list-mkod" );
			var message = $( ".toolbar-products" );
			var view = $( window );
			view.bind(
				"scroll resize",
				function(){
					var placeholderTop = placeholder.offset().top;
					var viewTop = view.scrollTop();
					if (viewTop > placeholderTop){
                        message.addClass( "toolbar-products-fixed" );

					} else if (viewTop <= placeholderTop){
						message.removeClass( "toolbar-products-fixed" );
					}
				}
			);

		});

	</script>
</script>