<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list trending-product">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title trending-product__title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content trending-product__content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?> box-list-product slideTrending owl-carousel owl-theme">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item) : ?>
                            <?= /* @noEscape */ ($iterator++ == 1) ? '<div class="product-item item">' : '</div><div class="product-item item">' ?>
                            <div class="product-item-info a-product">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo a-product__img">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-details a-product__info">
                                    <strong class="product-item-name name">
                                        <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                        href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                        class="product-item-link">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <div class="cate">
                                    <?php 
                                        $categoryId = $_item->getCategoryIds();
                                        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                        $category = $_objectManager->create('Magento\Catalog\Model\Category')
                                        ->load($categoryId);
                                        echo $category->getName();
                                    ?>
                                    </div>
                                    <?php if ($templateType) : ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?= $block->getProductPriceHtml($_item, $type) ?>

                                    <?= $block->getProductDetailsHtml($_item) ?>

                                    <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                        <div class="product-item-inner actions">
                                            <div class="view">
                                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">View</a>
                                            </div>
                                            <div class="box">
                                                <div class="line"></div>
                                            </div>
                                            <div class="product-item-actions buy">
                                                <?php if ($showCart) : ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()) : ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary button-link">
                                                                    <span class="action tocart primary buy-action"><?= $block->escapeHtml(__('Buy')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else : ?>
                                                            <?php if ($_item->getIsSalable()) : ?>
                                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                            <?php else : ?>
                                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                        </div>
                                                <?php endif; ?>
                                                
                                                <?php if ($showWishlist || $showCompare) : ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php //phpcs:disable ?>
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                    <?php //phpcs:enable ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                        <?php //phpcs:disable ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <?php //phpcs:enable ?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>                                               
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?= ($iterator == count($items) + 1) ? '</div>' : '' ?>
                        <?php endforeach ?>        
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>          
        </div>
    </div>
<?php endif;?>

<script type="text/javascript">
	require([
    'jquery',
    'owlcarousel'
], function($) {
    $('.slideTrending').owlCarousel({
        loop: true,
        nav: true,
        items: 5,
        navText: ["<img src='<?php echo $this->getViewFileUrl('images/pre.jpg'); ?>'>","<img src='<?php echo $this->getViewFileUrl('images/next.jpg'); ?>'>"],
        responsiveClass:true,
        responsive:{
            0:{
                items:1
            },
            680:{
                items:1,
                nav: false
            },
            768:{
                items:3,
                nav: false
            },
            1024:{
                items:4,
                nav: false
            },
            1366:{
                items:5
            }          
        }
    });
});
</script>